# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7236b2326d564aee61bd10f7ea7e35be923d2284a84cbb36868b76d59ce6afc8307db0117fc626a71834de970285bda031d9b0038e4c7e6a6e18825cb3490fd

test:
  secret_key_base: a563a03756c0ac75cc0d103999b89712c357db493cf9b14f8566270a6a9f6447b051c847c2f8f7d36b5e0c55a3c0f3d4977e2616fba9ccc13fb110056d925c67

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
